package.json
src/app/(auth)/login/page.tsx
src/app/(auth)/register/page.tsx
src/components/ui/form.tsx
src/components/ui/input.tsx
src/components/ui/label.tsx
tailwind.config.ts
yarn.lock

[#2] 로그인/회원가입 페이지

---

.vscode/settings.json
src/app/globals.css
src/app/layout.tsx
src/components/ui/button.tsx
src/components/ui/dialog.tsx

- 공용 컴포넌트 import 시 자동 완성에 radix ui가 나타나지 않도록 제외
- 모달 기본 스타일 작업
- 디자인 변경에 따라 공용헤더 기초 작업(추가 작업 필요)
- 모달을 띄울 트리거 컴포넌트 없이 핸들러로 모달을 띄울 수 있도록 개발 예정 
(현재 shadcn.ui에는 구현 안 되어있는 것 같아요)
#11

Feature 11/modal

---

package.json
src/lib/fetcher/index.ts
yarn.lock

- qs 라이브러리 추가
- fetcher GET 메서드 사용 시 쿼리스트링 처리 추가
- GET 사용하실 때 쿼리파라미터 필요하시면  params에 넣으시면 됩니다

GET 메서드 쿼리스트링 처리

---

.vscode/settings.json

-  tailwind 정렬 규칙 cva 함수 적용
<br/>
https://xionwcfm.tistory.com/325
<br/>

chore: tailwind 정렬 규칙 cva 함수 적용

---

src/app/(main)/_components/ChannelItem.tsx

#41 
<br/>
- 메인페이지(/)와 검색페이지(/search)에 Image 에러 수정하였습니다.
<br/>
- 메인페이지(/)와 검색페이지(/search)에 Image 에러 수정하였습니다.
<br/>
<br/>

Chore 41/image

---

src/app/channel/_components/playlist/PlaylistCard.tsx
src/app/globals.css
src/components/ui/dialog.tsx
src/components/ui/input.tsx
src/components/ui/label.tsx
tailwind.config.ts

- 디자인 시스템 변경 전 스타일 제거
<br/>
확인 후 머지 눌러주세요!

design: 미사용 스타일 제거

---

src/app/mypage/_components/EditMyInfo.tsx
src/components/ColorChips.tsx
src/components/TagInput.tsx
src/components/modal/CreateChannelModal.tsx
src/utils/hexToColorName.ts

#44 
- TagInput: 태그를 입력할 수 있는 컴포넌트
- hexToColorName: hex코드를 색상명으로 변환해주는 유틸 함수
- ColorChips 리팩토링
<br/>

ColorChips 리팩토링 및 TagInput 컴포넌트 추가

---

.gitignore
.husky/_/pre-commit
src/lib/fetcher/index.ts
src/services/channel/index.ts
src/services/channel/type.ts

- 변경된 API 타입 수정
- gitignore에서 .github, .husky/_ 추가된 사항 제거
- husky pre-commit 파일 추가

API 수정 및 gitignore 수정

---

src/components/TagInput.tsx
src/components/modal/CreateChannelModal.tsx
src/services/channel/index.ts
src/services/channel/type.ts

#45 
<br/>
- 채널 생성 API
- 채널생성모달 API 작업
<br/>
- 태그 삭제 기능 필요
- post 요청 보낼 때 accesstoken 처리 작업 필요
<br/>

Feature 44/create channel

---

src/app/auth/login/page.tsx
src/auth.ts
src/constants/domains.ts
src/services/auth/index.ts
src/services/user/index.ts

#10 
<br/>
- access_token을 cookies에서 못 가져오는 오류 해결
<br/>
- 'use server' 사용 필수
- 수정된 경로로 교체
<br/>
- 패칭하는 로직에 `use server`를 쓰셔야 쿠키사용가능합니다.
- 예시
```jsx
'use server'
import { cookies } from 'next/headers';
(...)
export const UserInfo = async () => {
const cookieStore = cookies();
const cookie = cookieStore.get('access_token')?.value;
console.log('cookie', cookie);
const data = await fetcher.get<GetUserResponse>(
`${DOMAIN.USER}/me`,
{},
{
headers: {
'Content-Type': 'application/json',
Authorization: `Bearer ${cookie}`,
},
},
);
// 잘 가져와짐
console.log('내정보내놔~:', data);
const { user } = data;
return user;
};
```
++ 로그인한 유저정보 필요하신 분은 로그인 후, zustand에 저장된 useUserStore()훅을 가져와서 사용하면 됩니다. 
<br/>

fix: cookies 에러 해결

---

src/components/Header.tsx
src/components/TagInput.tsx
src/components/modal/CreateChannelModal.tsx
src/components/ui/button.tsx
src/components/ui/input.tsx
src/services/channel/index.ts
src/services/channel/type.ts

#45 
<br/>
- 채널 생성 모달 라우팅 및 액세스 토큰 처리
- 태그 삭제 기능
- Header, button, input 컴포넌트 반응형 작업
<br/>

채널 생성모달 기능 추가 및 반응형 작업

---

src/app/mypage/_components/EditMyInfo.tsx
src/components/ColorChips.tsx
src/components/ui/input.tsx
src/services/user/index.ts

<br/>
회원 정보 수정 api 기능 구현
<br/>
- 모달 수정 필요
<br/>

Feature 57/mypage api

---

.eslintrc.json
src/app/channel/[channel_id]/error.tsx
src/components/ui/button.tsx
tailwind.config.ts

#67 
<br/>
- 존재하지 않는 채널에 대한 에러 페이지 추가
- hover, click 색상 추가 및 button 컴포넌트 적용
- eslint/no-unused-vars 규칙 off
<br/>
- no-unused-vars 규칙 거슬려서 껐습니다
<br/>

버튼 색상 추가 및 채널 에러페이지

---

next.config.mjs
src/components/ColorChips.tsx
src/components/TagInput.tsx

- TagInput 중복 태그 검사 및 문자열 공백 처리
- ColorChips 초기 색상 설정 방식 변경
<br/>
- Tag 입력 시 중복 태그가 있다면 추가 안 되도록 처리
- 태그 입력 시 공백 입력 불가
- ColorChips의 selected props로 초기 색상 설정 방식 변경
-  렌더링 시 onChange를 통해 selected hex색상이 전달됌.
<br/>

TagInput 기능 추가 및 ColorChips 변경

---

src/app/(main)/_components/GetUserInfo.tsx
src/app/auth/login/page.tsx
src/app/mypage/_components/EditMyInfo.tsx
src/app/page.tsx
src/auth.ts
src/services/user/index.ts
src/types/auth.d.ts
tsconfig.json

#77 
<br/>
- auth.ts의 로그인 유저정보 키값 추가 (session.user에 저장)
- next/headers의 cookies 삭제 -> session.user.accessToken 사용
- 로그인시 메인페이지로 이동했을 때, zustand에 유저정보 저장
<br/>
```tsx
'use client'
import { useSession } from 'next-auth/react';
(...)
const EditMyInfo = () => {
const { data: session } = useSession();
const UserInfo = async () => {
const accesstoken = session?.user.accessToken;
const data = await fetcher.get<GetUserResponse>(
`${DOMAIN.USER}/me`,
{},
{
headers: {
'Content-Type': 'application/json',
Authorization: `Bearer ${accesstoken}`,
},
},
);
console.log(data);
};
UserInfo();
(...)
}
```
```tsx
'use server'
import { auth } from '@/auth';
/** 회원 정보 조회 */
export const UserInfo = async () => {
const session = await auth();
const accesstoken = session?.user.accessToken;
const data = await …
```

Auth.js user 데이터 custom (accessToken 사용 방법 수정)

---

src/hooks/useSocket.ts
src/services/websocket/index.ts

웹소캣 accessToken 처리

---

src/auth.ts

#77 
<br/>
- 로그인 정보 틀렸을 경우 에러처리
<br/>
- Custom Error UI 있으면 좋을 것 같습니다.
<br/>

fix: 로그인 정보 틀렸을 경우 에러처리

---

src/lib/fetcher/index.ts

- fetcher 에러 메시지 수정
- 스택 트레이스, 서버 응답 데이터 확인 가능
- CustomError 적용
- 외부에서 catch문으로 에러 응답 처리할 수 있도록 적용
<br/>

refactor(fetcher): CustomError 처리

---

src/app/(main)/_components/ChannelList.tsx

#90 
<br/>
- /(main) 페이지의 channelList의 useSession 삭제하고 useUserStore로 변경하였습니다. 
<br/>
- /(main) 페이지의 channelList의 useSession 삭제하고 useUserStore로 변경하였습니다. 
<br/>
<br/>

Fix: channelList의 useSession 삭제하고 useUserStore로 변경

---

src/app/(main)/_components/ChannelItem.tsx
src/app/(main)/_components/ChannelList.tsx
src/app/channel/_components/chatting/index.tsx
src/app/error/_components/ErrorContent.tsx
src/app/error/layout.tsx
src/components/ui/input-otp.tsx
src/components/ui/textarea.tsx
src/stores/useMainStore.ts

- eslint import/order 에러 수정
- ChannelList 컴포넌트 useSession에 user.name이 없어서 발생하는 에러 수정
<br/>

fix: 에러 수정

---

src/app/mypage/_components/EditMyInfo.tsx
src/app/mypage/_components/PasswordCheck.tsx
src/components/modal/AlertModal.tsx
src/lib/fetcher/index.ts
src/services/user/index.ts
src/services/user/type.ts
src/services/websocket/index.ts
src/stores/User.ts

#92 
<br/>
- useUserStore profile_color 타입 에러 수정
- API 메서드 수정본 적용
- 데이터 패칭 성공시 모달 열리도록 수정
<br/>

Feature 92/mypage

---

src/services/websocket/index.ts

<br/>
- 웹소켓 서버URL 환경 변수 이름 수정
<br/>

fix: 웹소켓 서버URL 환경 변수 이름 수정

---

src/app/channel/_components/SocketConnector.tsx
src/app/channel/_components/chatting/index.tsx
src/services/websocket/index.ts
src/services/websocket/type.ts
src/stores/useSocketStore.ts

#87 
<br/>
- /channel/:channelId 유저 나감 구현하였습니다.
<br/>
- 채널 페이지 내 웹소켓 연결이 Disconnect 되면 유저가 나갔음을 서버 user.leave로 요청하도록 하였습니다. 
<br/>

Feat : /channel/:channelId 유저 나감 구현

---

src/components/TagInput.tsx
src/components/modal/CreateChannelModal.tsx
src/lib/fetcher/index.ts

- fetcher
- 채널생성모달: 채널 닫기 추가, 채널 생성 안 된 경우 alert
- 태그 입력 시 쉼표로 구분
<br/>
<br/>
<br/>

Tag input 수정

---

src/app/channel/_components/playlist/PlaylistCard.tsx
src/app/channel/_components/playlist/index.tsx

- 플레이리스트 줄바꿈 추가
- 플레이리스트 순서 변경 로직 수정
<br/>
- 플레이리스트 순서 변경 시 현재 재생되고 있는 영상 표시가 제대로 나타나도록 수정
<br/>

플레이리스트 순서 변경 로직 수정 및 줄바꿈

---

src/app/(main)/_components/Hashtags.tsx
src/services/channel/index.ts
src/services/channel/type.ts
src/services/user/index.ts

Fix : /(main) 페이지의 hashtag의 줄바꿈 해결 및 channelList관련 api 요청 코드에 revalidate 추가

---

src/services/channel/index.ts

- 채널 설정 모달
<br/>
- revalidate hook 사용으로 채널 수정시에도 데이터 바로 반영
<br/>

fix: revalidate hook 사용으로 채널 수정시에도 데이터 바로 반영

---

src/services/channel/index.ts

<br/>
- /services/channel의 충돌해결하다가 에러난 부분 수정하였습니다. 
<br/>

Fix: /services/channel의 충돌해결하다가 에러난 부분 수정

---

src/app/channel/_components/chatting/ChannelUsersModal.tsx
src/app/channel/_components/chatting/Message.tsx
src/app/channel/_components/chatting/UserSettingModal.tsx

Chore: api 없는 기능 삭제
